# Generated by Django 4.2.3 on 2023-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travorld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='explorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Desc', models.TextField()),
            ],
        ),
    ]
